filename = 'build/HDWallet.dmg'
volume_label = 'HDWallet'
format = 'UDZO'
filesystem = 'HFS+'
size = None
files = ['build/HDWallet.app']
symlinks = {'Applications': '/Applications'}
icon = '/Users/tsinatu/Documents/talonlab/hdwallet-desktop/src/ui/images/svg/HDW-Logo.svg'
background = 'src/ui/images/svg/HDW-Logo.svg'
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = 'auto'
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 16
icon_size = 128
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
